# This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Build (CI) and Auto-Merge (when Ready)

on:
    pull_request:
        branches: [main]

jobs:
    build:
        runs-on: ubuntu-latest

        strategy:
            matrix:
                node-version: [12.x, 14.x, 16.x, 19.x]

        steps:
            - name: Checkout repository
              uses: actions/checkout@v2

            - name: Set up Node.js ${{ matrix.node-version }}
              uses: actions/setup-node@v1
              with:
                  node-version: ${{ matrix.node-version }}

            - name: Restore node_modules from cache
              uses: actions/cache@v2
              with:
                  path: |
                      node_modules
                      */*/node_modules
                  key: ${{ runner.os }}-node_v${{ matrix.node-version }}-${{ hashFiles('**/yarn.lock') }}

            - name: Install dependencies
              run: npm install

            - name: Build
              run: npm run build
              env:
                  CI: false
    automerge:
        runs-on: ubuntu-latest
        needs:
            - build
        steps:
            - id: automerge
              name: automerge
              uses: "pascalgn/automerge-action@v0.15.5"
              env:
                  GITHUB_TOKEN: "${{ secrets.GITHUB_TOKEN }}"
